# Generated by Django 5.2.1 on 2025-05-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='release_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
